language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: nosetests
env:
  matrix:
  - TOKEN=FOO CHAT_ID=BAR
  global:
  - secure: bFAeg6mR5WKHo9Hrs0YpWn+l9UN/WaaziUmiu5G7f+8/qCP2AiRISv3Fu2rYWL5YIuQQf0zQ1vPCvt7RMVIOQOLyBgGgTji2XvX/E+BXRsFiUlse7mJV4OVfltat2yg66+L+G+Sy8dGslQfWs2hg/xAXP1W+gkBAkIuQELDb7GFEMMR4RBMj6a6K5ob3x7CAQSPqVqjI9+14DOVcO7t4xllqqEjSGqzid3Ma1/NuFFwjzJol4qbPb7ACAoRoR/Ocp8P8k1nyMZJsKcOhWCXocVgp/B3WRya9QeDujVHte17aq3U/AJH+eNBBVgoweFtFVEpBqtvynHChcDdbblgy5GrphhnXa71K5N82Gn6H1+D2D6sB+0+HIGlZthQnrvjZgSz2HsXh7tUI9HLWTOl8OXBKYnOoX9xYRPrsL+K+Z//e6yj14xf4leXp6T88QAW6AIuXmbX5ROVYVc7yeDZezsPgRXXmrerSVRyubzfzVAKoKBAcedcudjK7PJ8qSZEUyCRxZOM2VS80vOHKJnAoYnZscOwJCx6CFSkHRJ6Hrmf6dXdJRkfW0fkZqA3QWrPCO5ieF8G83x8B4SQpiREAndMPX10skt4vXtPjDFPdv5IBppcDkVGI+BHYWykMeF0UioWReeg2Dk7mG3GUEb9cKnHD5whvurmkb9rmZS22QO0=
  - secure: HHKL3VDATrwB9KOl3eA/DDvpPyknkX6bfYrleyF1nSTfyoRE1U2A9NkU+xvPIsszd3EjRc4rdQGNSG4fRPBMS5r3Cc0RosuLibAtoEXy5gd6QiQPo6hEANgZ5CV4TlmKHz2x8HyHzjYy4MEvorisF8pgPgJCeSkJLUV8tt7wEVBwN7XVgvfUxP1If4W/KGkloKPp2aCa5a7zZRAhF2iz1/NXrAwPXhgUeeTQYZQ+jSc0ni1ChhkNjhZ12t5vv7itaZREZ8qZIiBC6raFYS9I/aCk5O7GzLofrhv68JSpKAncKQP/VfDAnnWKzASVtx8OpU/MWsGxpflL6qUlhtbThds6plbnpAQI1k2qOKwPLZLF6FODNFvXFjdPpH+30PA7Bepd0ABGRQaEP4dQ9JQLBBy9V2rRjdBEp1pnqYygioMXamro9yLHtgkSVTo2thZb4XT/7kzU2cB3pF+64nU8THWcNlQtT836u8KvYzIBo3mo2/gcgXUHGc7h47Nwi4iPMyv0mLxhi56cEumUgbqC8R3rFLMBHmE5O69wJDc5pPVjpsLvn/Z8vnr1XWJdCcFsMr2LLwK7/oNkj4ReufzdQRo7lmLOiPkKWYhiyZ4NQUrztzRMOqoVwH/23v0PROkbdym5G150wo3YZvXVbmmK64As8JvQs2sQ53IL9CsX6gE=
after_success:
  - ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no $SSH_LOGIN:$SSH_PASS@dun.ai 'pwd'
